### ISSUE TITLE
update 'Hub Ready' checklist doc for this app

### ISSUE THREAD

**Issue by jgravois** [Esri/MyStreet#28]
linking to other centralized public AGOL and Hub documentation

**Comment by jgravois** [comment]
assign to me or give me 🔑 s please

**Comment by jgravois** [comment]
work in progress: https://github.com/jgravois/hub-ready-apps

**Comment by jgravois** [comment]
jgravois/[hub-ready-apps](https://github.com/jgravois/hub-ready-apps) > 🔐   ArcGIS/[hub-ready-apps](https://github.com/ArcGIS/hub-ready-apps) > 🔓  Esri/hub-ready-apps (hopefully soon)

**Comment by MarkhamShofner** [comment]
will be resolved by https://github.com/Esri/MyStreet/pull/35
