### ISSUE TITLE
deprecate this project?

### ISSUE THREAD

**Issue by tomwayson** [Esri/MyStreet#45]
I don't believe this is maintained any longer, right @MarkhamShofner?

**Comment by MarkhamShofner** [comment]
It's not aggressively maintained @tomwayson but I gave it a dependencies facelift a few weeks back and got the thing running again at the request of a customer.

**Comment by thomas-hervey** [comment]
@tomwayson and @MarkhamShofner, just want to let you know that @ajturner and I discussed this the other day as a potential springboard for the next gen of Hub search. I'll be playing around with the functionality in the weeks to come.
